ServiceProviderApplication/Controllers/ConsumerController.cs
using ServiceProviderApplication.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiceProviderApplication.Controllers
{
    public class ConsumerController : BaseController
    {
        private const string UniqueKeyErrorMessage = "The Key field must be unique";

        public ConsumerController() { }

        public ConsumerController(ProviderContext providerContext) : base(providerContext) { }

        //
        // GET: /Consumer/

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Consumers.ToList());
        }

        //
        // GET: /Consumer/Details/5

        public ActionResult Details(int id = 0)
        {
            Consumer consumer = db.Consumers.Find(id);
            if (consumer == null)
            {
                return HttpNotFound();
            }
            return View(consumer);
        }

        //
        // GET: /Consumer/Create

        public ActionResult Create()
        {
            Consumer consumer = new Consumer();
            consumer.Key = Guid.NewGuid().ToString("N").Substring(0, 16);
            consumer.Secret = Guid.NewGuid().ToString("N").Substring(0, 16);
            return View(consumer);
        }

        //
        // POST: /Consumer/Create

        [HttpPost]
        public ActionResult Create(Consumer consumer)
        {
            if (ModelState.IsValid)
            {
                // Make sure the user did not create a non-unique key
                var match = db.Consumers.SingleOrDefault(
                    c => c.Key == consumer.Key);
                if (match != null)
                {
                    ModelState.AddModelError("Key", UniqueKeyErrorMessage);
                }
                else
                {
                    db.Consumers.Add(consumer);
                    db.SaveChanges();
                    if (string.IsNullOrEmpty(Request["ReturnURL"]))
                    {
                        return RedirectToAction("Index");
                    }
                    var uri = new UriBuilder(Request["ReturnURL"]);
                    uri.Query += "ConsumerId=" + consumer.ConsumerID;
                    return Redirect(uri.ToString());
                }
            }
            return View(consumer);
        }

        //
        // GET: /Consumer/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Consumer consumer = db.Consumers.Find(id);
            if (consumer == null)
            {
                return HttpNotFound();
            }
            return View(consumer);
        }

        //
        // POST: /Consumer/Edit/5

        [HttpPost]
        public ActionResult Edit(Consumer consumer)
        {
            if (ModelState.IsValid)
            {
                // Make sure the user did not change the Key to
                // a non-unique value
                var match = db.Consumers.SingleOrDefault(
                    c => c.Key == consumer.Key && c.ConsumerID != consumer.ConsumerID);
                if (match != null)
                {
                    ModelState.AddModelError("Key", UniqueKeyErrorMessage);
                }
                else
                {
                    db.Entry(consumer).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(consumer);
        }

        //
        // GET: /Consumer/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Consumer consumer = db.Consumers.Find(id);
            if (consumer == null)
            {
                return HttpNotFound();
            }
            return View(consumer);
        }

        //
        // POST: /Consumer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Consumer consumer = db.Consumers.Find(id);
            db.Consumers.Remove(consumer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ServiceProviderApplication/Controllers/UserController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using ServiceProviderApplication.Models;
using System.Diagnostics;

namespace ServiceProviderApplication.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public UserController() { }

        public UserController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        //
        // GET: /User/
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /User/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // GET: /User/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                id = User.Identity.GetUserId();
            }
            var user = await UserManager.FindByIdAsync(id);
            var model = new UserProfileModel(user);
            model.IsStudent = await UserManager.IsInRoleAsync(user.Id, UserRoles.StudentRole);
            model.IsTeacher = await UserManager.IsInRoleAsync(user.Id, UserRoles.TeacherRole);
            return View(model);
        }

        //
        // POST: /User/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(UserProfileModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(model.UserID);
                user.Email = model.Email;
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;

                await UserManager.UpdateAsync(user);

                await UpdateUserRole(user.Id, UserRoles.StudentRole, model.IsStudent);
                await UpdateUserRole(user.Id, UserRoles.TeacherRole, model.IsTeacher);

                if (User.Identity.GetUserId() == user.Id)
                {
                    var claimsIdentity = await UserManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
                    Request.GetOwinContext().Authentication.SignIn(claimsIdentity);
                }

                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        private async Task UpdateUserRole(string userId, string roleName, bool userIsInRole)
        {
            Debug.WriteLine("{0} is in role {1}: {2}", userId, roleName, await UserManager.IsInRoleAsync(userId, roleName));
            if (userIsInRole)
            {
                if (!await UserManager.IsInRoleAsync(userId, roleName))
                    await UserManager.AddToRoleAsync(userId, roleName);
            }
            else
            {
                if (await UserManager.IsInRoleAsync(userId, roleName))
                    await UserManager.AddToRoleAsync(userId, roleName);
            }
        }

        //
        // GET: /User/Delete/5
        [Authorize(Roles = "SuperUser")]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /User/Delete/5
        [Authorize(Roles = "SuperUser")]
        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var user = await UserManager.FindByIdAsync(id);

            // Remove this user from any roles they may have
            foreach (var role in user.Roles)
            {
                await UserManager.RemoveFromRoleAsync(user.Id, role.ToString());
            }
            // Remove the user's account
            var _result = await UserManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
    }
}

ServiceProviderApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LTI Provider</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LTI Provider", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Consumers", "Index", "Consumer")</li>
                        <li>@Html.ActionLink("Tools", "Index", "Tool")</li>
                        if (User.IsInRole(ServiceProviderApplication.Models.UserRoles.AdminRole))
                        {
                            <li>@Html.ActionLink("Users", "Index", "User")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LTI Provider</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ServiceProviderApplication/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - LTI Tool Provider</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

ServiceProviderApplication/Views/Shared/_LayoutSearch.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LTI Tool Provider</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">LTI Tool Provider</div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Copyright &copy; @DateTime.Now.Year. This work is licensed under an <a rel="license" href="http://www.apache.org/licenses/">Apache License 2.0</a>.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ServiceProviderApplication/Views/Shared/_LayoutView.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        body {
            padding-top: 0;
        }
    </style>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Copyright &copy; @DateTime.Now.Year. This work is licensed under an <a rel="license" href="http://www.apache.org/licenses/">Apache License 2.0</a>.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>